aff<-read.csv(choose.files(),header = T)
head(aff)
aff<-aff[,-c(1,14:19)]
head(aff)
str(aff)
aff$extramaterial.affairs<-factor(aff$extramaterial.affairs)
library(caTools)
set.seed(123)
spl<-sample.split(aff$extramaterial.affairs,SplitRatio = 0.75)
trn<-subset(aff,spl==T)
tst<-subset(aff,spl==F)
aff_reg<-glm(extramaterial.affairs~.,data=trn,family = binomial)
aff_pred<-predict(aff_reg,newdata=tst, type = "response")
aff_pred<-ifelse(aff_pred>=0.5,1,0)
aff_pred
cnfm<-table(tst$extramaterial.affairs,aff_pred)
library(caret)
library(e1071)
confusionMatrix(cnfm)
